### ISSUE TITLE
Return a `CDataModel` for `CalllingConvention::AppleAarch64`

### ISSUE THREAD

**Issue by Spartan2909** [bytecodealliance/target-lexicon#100]
According to [Apple's documentation](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms), their C data model seems to conform to LP64.

[This Wikipedia article](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) also says that macOS uses LP64.

Unless I've missed something, it should be possible to simply return `CDataModel::LP64` from `Triple::data_model` when the calling convention is `AppleAarch64`.

I'm happy to open a PR for this if this is the right solution.

**Comment by sunfishcode** [comment]
This is now released in target-lexicon 0.12.15.
