### ISSUE TITLE
Make a distinction between LLVM and rustc target triples

### ISSUE THREAD

**Issue by madsmtm** [bytecodealliance/target-lexicon#111]
It isn't really clear from the documentation whether this crate parses LLVM or rustc target triples, and that's probably because it tries to parse both.

This is problematic though, in particular the triple `aarch64-apple-darwin` is from my understanding ambiguous?
- In LLVM's case refers to "the generic [Darwin](https://en.wikipedia.org/wiki/Darwin_(operating_system)) platform, i.e. any of macOS/iOS/tvOS/watchOS/visionOS" (from my experiments, the LLVM target is mostly defunct by itself). The macOS triple is `aarch64-apple-macosx`.
- When using Clang, the chosen platform depends on the currently active SDK, and/or the presence of other flags like `-miphoneos-version-min=...`.
- In rustc's case it refers to "the macOS platform".

Would it make sense to say "`FromStr` only parses `rustc` triples", or "`FromStr` only parses LLVM triples"? Or maybe add `Triple::from_llvm(&str) -> Result<Self>` and `Triple::from_rustc(&str) -> Result<Self>`, and remove `FromStr`?

**Comment by madsmtm** [comment]
Another solution would be to rename `rustc`'s macOS targets to `*-apple-macos`, which is desirable anyhow. But that's a complicated process.

**Comment by madsmtm** [comment]
This is also relevant for figuring out how to parse deployment targets for iOS/tvOS/watchOS/visionOS targets (since what we do here depends on what `target-lexicon` intends on supporting).

**Comment by madsmtm** [comment]
I see that this has also been discussed a bit in https://github.com/bytecodealliance/target-lexicon/issues/78.

**Comment by sunfishcode** [comment]
target-lexicon was written at a time when there was a combination of a lack of alternatives, and a lack of understanding on my part of the relationship between rust target names and LLVM target names.

If one only wants to work with Rust target names now, it may be better to switch to the [platforms crate](https://docs.rs/platforms/latest/platforms/) instead.

Perhaps this means that target-lexicon should ideally migrate to focusing only on LLVM target names.
