### ISSUE TITLE
failure with musl libc

### ISSUE THREAD

**Issue by anarchpenguin** [bytecodealliance/target-lexicon#33]
20:49.44      Running `/var/tmp/portage/www-client/firefox-71.0_beta6/work/firefox-71.0/ff/release/build/target-lexicon-f3f06bed553e79f7/build-script-build`
20:49.46 [target-lexicon 0.8.1] thread 'main' panicked at 'can't find custom target x86_64-gentoo-linux-musl', /var/tmp/portage/www-client/firefox-71.0_beta6/work/firefox-71.0/third_party/rust/target-lexicon/build.rs:100:5
20:49.46 [target-lexicon 0.8.1] stack backtrace:
20:49.46 [target-lexicon 0.8.1]    0:     0x563128709e21 - std::sys_common::backtrace::print::h287c8c07a68eede3
20:49.46 [target-lexicon 0.8.1]    1:     0x56312870d6c2 - std::panicking::default_hook::{{closure}}::h05f6680debc806b6
20:49.46 [target-lexicon 0.8.1]    2:     0x56312870d460 - std::panicking::default_hook::h15544f9c95b669ca
20:49.46 [target-lexicon 0.8.1]    3:     0x56312870dcfd - std::panicking::rust_panic_with_hook::h3c1da02a49e9001b
20:49.46 [target-lexicon 0.8.1]    4:     0x56312870d892 - std::panicking::continue_panic_fmt::h1225421fdef1e090
20:49.46 [target-lexicon 0.8.1]    5:     0x56312870d7df - std::panicking::begin_panic_fmt::h6cf338a46e92138b
20:49.46 [target-lexicon 0.8.1]    6:     0x5631286ffe28 - build_script_build::main::h2d1c6843c8761064
20:49.47 [target-lexicon 0.8.1]    7:     0x5631286f9173 - std::rt::lang_start::{{closure}}::h2de0c3e376b0d62e
20:49.47 [target-lexicon 0.8.1]    8:     0x56312870d763 - std::panicking::try::do_call::h303cc4ae6bb6cb3c
20:49.47 [target-lexicon 0.8.1]    9:     0x56312870e4ba - __rust_maybe_catch_panic
20:49.47 [target-lexicon 0.8.1]   10:     0x563128706e54 - std::rt::lang_start_internal::he20f95ac4ef5d8da
20:49.47 [target-lexicon 0.8.1]   11:     0x563128702b12 - main
20:49.47 [target-lexicon 0.8.1]   12:     0x7fa1617c9b55 - <unknown>
20:49.47 error: failed to run custom build command for `target-lexicon v0.8.1`
20:49.48 Caused by:
20:49.48   process didn't exit successfully: `/var/tmp/portage/www-client/firefox-71.0_beta6/work/firefox-71.0/ff/release/build/target-lexicon-f3f06bed553e79f7/build-script-build` (exit code: 101)
20:49.48 --- stderr
20:49.48 thread 'main' panicked at 'can't find custom target x86_64-gentoo-linux-musl', /var/tmp/portage/www-client/firefox-71.0_beta6/work/firefox-71.0/third_party/rust/target-lexicon/build.rs:100:5
20:49.48 stack backtrace:
20:49.48    0:     0x563128709e21 - std::sys_common::backtrace::print::h287c8c07a68eede3
20:49.48    1:     0x56312870d6c2 - std::panicking::default_hook::{{closure}}::h05f6680debc806b6
20:49.48    2:     0x56312870d460 - std::panicking::default_hook::h15544f9c95b669ca
20:49.48    3:     0x56312870dcfd - std::panicking::rust_panic_with_hook::h3c1da02a49e9001b
20:49.49    4:     0x56312870d892 - std::panicking::continue_panic_fmt::h1225421fdef1e090
20:49.49    5:     0x56312870d7df - std::panicking::begin_panic_fmt::h6cf338a46e92138b
20:49.49    6:     0x5631286ffe28 - build_script_build::main::h2d1c6843c8761064
20:49.49    7:     0x5631286f9173 - std::rt::lang_start::{{closure}}::h2de0c3e376b0d62e
20:49.49    8:     0x56312870d763 - std::panicking::try::do_call::h303cc4ae6bb6cb3c
20:49.49    9:     0x56312870e4ba - __rust_maybe_catch_panic
20:49.49   10:     0x563128706e54 - std::rt::lang_start_internal::he20f95ac4ef5d8da
20:49.49   11:     0x563128702b12 - main
20:49.49   12:     0x7fa1617c9b55 - <unknown>

**Comment by mjeveritt** [comment]
Looks like it's baulking at the 'vendor' field being "Gentoo" .. see https://github.com/CraneStation/target-lexicon/blob/master/src/targets.rs#L297 :)

**Comment by sunfishcode** [comment]
Neither LLVM nor Rust recognizes a "gentoo" vendor field, so I'm not sure what this is offhand. Does anyone know how x86_64-gentoo-linux-musl differs from x86_64-unknown-linux-musl?

**Comment by anarchpenguin** [comment]
> Neither LLVM nor Rust recognizes a "gentoo" vendor field, so I'm not sure what this is offhand. Does anyone know how x86_64-gentoo-linux-musl differs from x86_64-unknown-linux-musl?

Gentoo is the vendor which is heavily patched compared to that of rustup, arch linux is gonna experience the same issue.

**Comment by smaeul** [comment]
> Neither LLVM nor Rust recognizes a "gentoo" vendor field, so I'm not sure what this is offhand. Does anyone know how x86_64-gentoo-linux-musl differs from x86_64-unknown-linux-musl?

Yes. [The difference is](https://github.com/smaeul/rust/commit/455d40a88ff529188ca8418a83bf66f7b240bd01#diff-21c7838a9b7afd6e442cc0f62c4a6b4f) `base.options.crt_static_default = false;`. This is the same for [the Adélie target](https://code.foxkit.us/adelie/packages/blob/master/user/rust/0016-Add-foxkit-target-specs.patch#L133). [The Alpine target](https://git.alpinelinux.org/aports/tree/community/rust/alpine-target.patch#n107) makes that change and also enables static PIE. The reason for these custom targets is to avoid modifying the "official" target, which links statically by default, and therefore isn't suitable for a Linux distribution.

But the differences are irrelevant. As the comment in your code (linked above), `Vendor` is "an arbitrary modifier". You can't enumerate the values, because any alphanumeric string is valid. You need a `Custom(String)` in your `Vendor` enum.

**Comment by awilfox** [comment]
See also #12, where I raised this issue long ago (but didn't know that `Custom(String)` was a thing at the time).

**Comment by sunfishcode** [comment]
Thanks to folks for the explanations here! I've now also done a little research into how other tools handle these custom vendor strings, and the result is I think it does make sense to support them in `target-lexicon` too. I've now created #35 with a prototype implementation.
