### ISSUE TITLE
Add a different calling-convention for Mac Aarch64

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/target-lexicon#69]
MacOS Aarch64 uses the same ARM64 calling convention *with tweaks*: https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms

Returning a different default `CallingConvention` for this triple would be a nice way to signal users that they might require handling it particularly.

**Comment by sunfishcode** [comment]
Makes sense! I've now submitted #70 to implement this.
