### ISSUE TITLE
release a new "major"?

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/target-lexicon#71]
Turns out that adding the aarch64 darwin calling convention in #70 is a breaking API change: in wasmtime, which targets 0.11 of this library, and thus uses the latest patch version, this causes an assertion failure that the calling convention is unknown, because it isn't properly handled yet (I'll take care of this). The same issue could happen to other target_lexicon users, so it might require a new "major" release of target-lexicon to indicate this breaking change happened.

Since this crate is still pre 1.0, a new "major" release consists in bumping what's otherwise the "minor" number, so it should be 0.12.

**Comment by sunfishcode** [comment]
Most of the enums in target-lexicon are marked `non_exhaustive`, however it appears I overlooked `CallingConvention`. I've now submitted https://github.com/bytecodealliance/target-lexicon/pull/72 to fix that.

Once that lands, I'll do a 0.12 release and yank 0.11.3.

**Comment by sunfishcode** [comment]
Ok, 0.12 is now up, and 0.11.3 is now yanked.
