### ISSUE TITLE
Support for TARGET const

### ISSUE THREAD

**Issue by hug-dev** [bytecodealliance/target-lexicon#73]
Hello 👋 

First of all, thanks for your crate! Really useful and I think we are going to use it to fix [our issue](https://github.com/parallaxsecond/rust-cryptoki/issues/15) (parsing the target architecture + OS to select the correct `bindgen` binding).

I am not sure if it possible but similarly to the `HOST` constant, it would be nice to have a `TARGET` one which is:
```rust
target_lexicon::Triple::from_str(&std::env::var("TARGET").unwrap());
```
so that it can be used directly 😃 Maybe it already exists or was already thoguht about but a quick search in the repo did not yield anything!

**Comment by bjorn3** [comment]
When you are using target-lexicon as dependency for a build script, the build script of target-lexicon will only see what the host is. The `TARGET` env var for the target-lexicon build script will be the host system. There is nothing target-lexicon can do about this. You could define a convenience function in bindgen though:

```rust
fn target_triple() -> target_lexicon::Triple {
    target_lexicon::Triple::from_str(&std::env::var("TARGET").unwrap());
}
```

**Comment by hug-dev** [comment]
ah right I see. No worries then 👍

**Comment by nayeemrmn** [comment]
> When you are using target-lexicon as dependency for a build script, the build script of target-lexicon will only see what the host is. The `TARGET` env var for the target-lexicon build script will be the host system.

What if it's not a dependency of the build script but a runtime dependency? Would that give the correct target?

**Comment by bjorn3** [comment]
Yes, in that case target-lexicon itself will be built for the target rather than the host and as such the `TARGET` env var will be set to the target when running target-lexicon's build script.

**Comment by nayeemrmn** [comment]
So does it make sense to add this const?

**Comment by nayeemrmn** [comment]
The use case for me is to reference the target triple at runtime _without_ using a build.rs, in a crate which doesn't otherwise need one.

**Comment by bjorn3** [comment]
`target_lexicon::HOST` gives the triple for whatever target target-lexicon (and thus also your crate that depends on target-lexicon) was built with.

**Comment by nayeemrmn** [comment]
Ah, so `target_lexicon::HOST` is based on the `TARGET` var, but is named `HOST` to not confuse those who are using it as a build dependency. So it would work for my case.

It's still worth considering moving `target_lexicon::HOST` to be based on the `HOST` var and adding `target_lexicon::TARGET` with the current definition of `target_lexicon::HOST`. With an emphatic warning in the docstring that `TARGET` won't work as expected from a build dependency. Maybe this issue could be reopened.

**Comment by bjorn3** [comment]
At compile time you have:

* Host: The triple for which rustc itself and build scripts are compiled.
* Target: The triple for which you are compiling the program.

At runtime you have:

* Host: The triple for which the program is compiled. This is the same as the "target" at compile time.
* Target: Doesn't exist unless you are a compiled yourself and even then likely determined at runtime.

target_lexicon names `HOST` from a runtime perspective. The compile time "host" is almost never relevant at runtime and most likely shouldn't end up in the final executable for reproducible builds when cross-compiling. In case of depending on target-lexicon build scripts `HOST` is correctly named as it is the triple for which the build script itself was compiled. target-lexicon can't know which target the final program will be compiled for, so you have to read the `TARGET` env var at runtime and parse it.
